// ============================================================
// CapitalForge — Card Products Seed Data
//
// Run: npx tsx prisma/seeds/card-products.ts
//
// Seeds 24 business credit cards from top issuers and credit unions with
// realistic data for limits, APR, fees, score requirements.
// Idempotent: uses upsert keyed on name + issuerId.
// ============================================================

import { PrismaClient, Prisma } from '@prisma/client';

const prisma = new PrismaClient();

function dec(value: string | number): Prisma.Decimal {
  return new Prisma.Decimal(String(value));
}

interface CardSeed {
  issuerId: string;
  name: string;
  cardType: 'business_credit' | 'business_charge' | 'secured';
  annualFee: number;
  annualFeeWaivedY1: boolean;
  aprIntro: number | null;
  aprIntroMonths: number | null;
  aprPostPromo: number | null;
  creditLimitMin: number;
  creditLimitMax: number;
  creditLimitTypical: number;
  scoreMinimum: number;
  revenueMinimum: number;
  businessAgeMinimum: number;
  rewardsType: string | null;
  rewardsRate: number | null;
  rewardsDetails: string | null;
  welcomeBonus: string | null;
  welcomeBonusValue: number | null;
  personalGuarantee: boolean;
  approvalDifficulty: 'easy' | 'moderate' | 'hard' | 'very_hard';
  bestFor: string | null;
  notes: string | null;
}

const CARD_SEEDS: CardSeed[] = [
  // ── Chase ────────────────────────────────────────────────
  {
    issuerId: 'chase',
    name: 'Chase Ink Business Cash',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 12,
    aprPostPromo: 18.49,
    creditLimitMin: 3000,
    creditLimitMax: 25000,
    creditLimitTypical: 12000,
    scoreMinimum: 680,
    revenueMinimum: 50000,
    businessAgeMinimum: 12,
    rewardsType: 'cash_back',
    rewardsRate: 5.0,
    rewardsDetails: '5% on office supplies & telecom (first $25K/yr), 2% on gas & restaurants (first $25K/yr), 1% all other',
    welcomeBonus: '$750 cash back after $6,000 spend in 3 months',
    welcomeBonusValue: 750,
    personalGuarantee: true,
    approvalDifficulty: 'moderate',
    bestFor: 'Office supply and telecom spending',
    notes: 'Subject to Chase 5/24 rule',
  },
  {
    issuerId: 'chase',
    name: 'Chase Ink Business Preferred',
    cardType: 'business_credit',
    annualFee: 95,
    annualFeeWaivedY1: false,
    aprIntro: null,
    aprIntroMonths: null,
    aprPostPromo: 21.24,
    creditLimitMin: 5000,
    creditLimitMax: 50000,
    creditLimitTypical: 20000,
    scoreMinimum: 700,
    revenueMinimum: 75000,
    businessAgeMinimum: 12,
    rewardsType: 'points',
    rewardsRate: 3.0,
    rewardsDetails: '3x on travel, shipping, internet, cable, phone, and ads (first $150K/yr combined), 1x all other',
    welcomeBonus: '100,000 Ultimate Rewards points after $8,000 spend in 3 months',
    welcomeBonusValue: 1250,
    personalGuarantee: true,
    approvalDifficulty: 'hard',
    bestFor: 'Travel and advertising spend',
    notes: 'Subject to Chase 5/24 rule. Points worth 1.25cpp via portal.',
  },
  {
    issuerId: 'chase',
    name: 'Chase Ink Business Unlimited',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 12,
    aprPostPromo: 18.49,
    creditLimitMin: 3000,
    creditLimitMax: 25000,
    creditLimitTypical: 10000,
    scoreMinimum: 680,
    revenueMinimum: 50000,
    businessAgeMinimum: 12,
    rewardsType: 'cash_back',
    rewardsRate: 1.5,
    rewardsDetails: '1.5% unlimited cash back on all purchases',
    welcomeBonus: '$750 cash back after $6,000 spend in 3 months',
    welcomeBonusValue: 750,
    personalGuarantee: true,
    approvalDifficulty: 'moderate',
    bestFor: 'Simple flat-rate rewards with 0% intro APR',
    notes: 'Subject to Chase 5/24 rule',
  },

  // ── American Express ─────────────────────────────────────
  {
    issuerId: 'amex',
    name: 'Amex Business Gold Card',
    cardType: 'business_charge',
    annualFee: 375,
    annualFeeWaivedY1: false,
    aprIntro: null,
    aprIntroMonths: null,
    aprPostPromo: null,
    creditLimitMin: 10000,
    creditLimitMax: 0, // no preset spending limit
    creditLimitTypical: 25000,
    scoreMinimum: 700,
    revenueMinimum: 100000,
    businessAgeMinimum: 12,
    rewardsType: 'points',
    rewardsRate: 4.0,
    rewardsDetails: '4x on top 2 eligible spend categories each billing cycle (first $150K/yr), 1x all other',
    welcomeBonus: '100,000 Membership Rewards points after $15,000 spend in 3 months',
    welcomeBonusValue: 1000,
    personalGuarantee: true,
    approvalDifficulty: 'hard',
    bestFor: 'High-volume category spending',
    notes: 'Charge card — no preset limit. Subject to Amex 2/90 velocity rule.',
  },
  {
    issuerId: 'amex',
    name: 'Amex Business Platinum Card',
    cardType: 'business_charge',
    annualFee: 695,
    annualFeeWaivedY1: false,
    aprIntro: null,
    aprIntroMonths: null,
    aprPostPromo: null,
    creditLimitMin: 15000,
    creditLimitMax: 0,
    creditLimitTypical: 50000,
    scoreMinimum: 720,
    revenueMinimum: 200000,
    businessAgeMinimum: 24,
    rewardsType: 'points',
    rewardsRate: 5.0,
    rewardsDetails: '5x on flights & prepaid hotels via Amex Travel, 1.5x on purchases $5K+, 1x all other',
    welcomeBonus: '150,000 Membership Rewards points after $20,000 spend in 3 months',
    welcomeBonusValue: 1500,
    personalGuarantee: true,
    approvalDifficulty: 'very_hard',
    bestFor: 'Premium travel benefits and high-value purchases',
    notes: 'Charge card. Extensive travel perks. Subject to Amex 2/90 velocity rule.',
  },
  {
    issuerId: 'amex',
    name: 'Amex Blue Business Cash',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 12,
    aprPostPromo: 18.49,
    creditLimitMin: 2000,
    creditLimitMax: 20000,
    creditLimitTypical: 10000,
    scoreMinimum: 670,
    revenueMinimum: 50000,
    businessAgeMinimum: 6,
    rewardsType: 'cash_back',
    rewardsRate: 2.0,
    rewardsDetails: '2% cash back on first $50,000/yr purchases, 1% after',
    welcomeBonus: '$250 statement credit after $3,000 spend in 3 months',
    welcomeBonusValue: 250,
    personalGuarantee: true,
    approvalDifficulty: 'moderate',
    bestFor: 'No-fee card with solid flat cash back',
    notes: 'Subject to Amex 2/90 velocity rule.',
  },
  {
    issuerId: 'amex',
    name: 'Amex Blue Business Plus',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 15,
    aprPostPromo: 18.49,
    creditLimitMin: 2000,
    creditLimitMax: 20000,
    creditLimitTypical: 10000,
    scoreMinimum: 670,
    revenueMinimum: 50000,
    businessAgeMinimum: 6,
    rewardsType: 'points',
    rewardsRate: 2.0,
    rewardsDetails: '2x Membership Rewards on first $50,000/yr, 1x after',
    welcomeBonus: '15,000 MR points after $3,000 spend in 3 months',
    welcomeBonusValue: 150,
    personalGuarantee: true,
    approvalDifficulty: 'moderate',
    bestFor: 'Longest 0% intro APR with Membership Rewards earning',
    notes: 'Subject to Amex 2/90 velocity rule. 15 months 0% APR is one of the longest.',
  },

  // ── Capital One ──────────────────────────────────────────
  {
    issuerId: 'capital_one',
    name: 'Capital One Spark Cash Plus',
    cardType: 'business_charge',
    annualFee: 150,
    annualFeeWaivedY1: false,
    aprIntro: null,
    aprIntroMonths: null,
    aprPostPromo: null,
    creditLimitMin: 10000,
    creditLimitMax: 100000,
    creditLimitTypical: 30000,
    scoreMinimum: 700,
    revenueMinimum: 100000,
    businessAgeMinimum: 24,
    rewardsType: 'cash_back',
    rewardsRate: 2.0,
    rewardsDetails: '2% unlimited cash back on all purchases',
    welcomeBonus: '$1,200 cash bonus after $30,000 spend in 3 months',
    welcomeBonusValue: 1200,
    personalGuarantee: true,
    approvalDifficulty: 'hard',
    bestFor: 'Highest flat-rate cash back with no cap',
    notes: 'Charge card — must pay in full. High credit limits available.',
  },
  {
    issuerId: 'capital_one',
    name: 'Capital One Spark Miles for Business',
    cardType: 'business_credit',
    annualFee: 95,
    annualFeeWaivedY1: false,
    aprIntro: null,
    aprIntroMonths: null,
    aprPostPromo: 26.24,
    creditLimitMin: 5000,
    creditLimitMax: 50000,
    creditLimitTypical: 15000,
    scoreMinimum: 680,
    revenueMinimum: 75000,
    businessAgeMinimum: 12,
    rewardsType: 'miles',
    rewardsRate: 2.0,
    rewardsDetails: '5x on hotels/rental cars via Capital One Travel, 2x all other purchases',
    welcomeBonus: '50,000 miles after $4,500 spend in 3 months',
    welcomeBonusValue: 500,
    personalGuarantee: true,
    approvalDifficulty: 'moderate',
    bestFor: 'Travel rewards with flexible transfer partners',
    notes: null,
  },

  // ── Citi ─────────────────────────────────────────────────
  {
    issuerId: 'citi',
    name: 'Citi Business AAdvantage Platinum Select',
    cardType: 'business_credit',
    annualFee: 99,
    annualFeeWaivedY1: true,
    aprIntro: null,
    aprIntroMonths: null,
    aprPostPromo: 21.24,
    creditLimitMin: 3000,
    creditLimitMax: 30000,
    creditLimitTypical: 12000,
    scoreMinimum: 680,
    revenueMinimum: 50000,
    businessAgeMinimum: 12,
    rewardsType: 'miles',
    rewardsRate: 2.0,
    rewardsDetails: '2x AAdvantage miles on AA purchases, cable/satellite/telecom, gas, car rentals; 1x all other',
    welcomeBonus: '65,000 AAdvantage miles after $4,000 spend in 4 months',
    welcomeBonusValue: 975,
    personalGuarantee: true,
    approvalDifficulty: 'moderate',
    bestFor: 'American Airlines loyalty and business travel',
    notes: 'Citi 1/8 rule: max 1 Citi card per 8 days. Also Citi 2/65 rule.',
  },

  // ── Bank of America ──────────────────────────────────────
  {
    issuerId: 'bank_of_america',
    name: 'Bank of America Business Advantage Cash Rewards',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 9,
    aprPostPromo: 18.49,
    creditLimitMin: 1000,
    creditLimitMax: 25000,
    creditLimitTypical: 8000,
    scoreMinimum: 660,
    revenueMinimum: 25000,
    businessAgeMinimum: 6,
    rewardsType: 'cash_back',
    rewardsRate: 3.0,
    rewardsDetails: '3% on choice category (gas, office, travel, etc.) first $50K/yr, 2% dining, 1% all other',
    welcomeBonus: '$300 statement credit after $3,000 spend in 90 days',
    welcomeBonusValue: 300,
    personalGuarantee: true,
    approvalDifficulty: 'easy',
    bestFor: 'Flexible category bonus for small businesses',
    notes: 'Preferred Rewards for Business can boost cash back by 25-75%.',
  },
  {
    issuerId: 'bank_of_america',
    name: 'Bank of America Business Advantage Travel Rewards',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 9,
    aprPostPromo: 18.49,
    creditLimitMin: 1000,
    creditLimitMax: 20000,
    creditLimitTypical: 7000,
    scoreMinimum: 660,
    revenueMinimum: 25000,
    businessAgeMinimum: 6,
    rewardsType: 'points',
    rewardsRate: 1.5,
    rewardsDetails: '3x via BofA Travel Center, 1.5x all other purchases',
    welcomeBonus: '30,000 points after $3,000 spend in 90 days',
    welcomeBonusValue: 300,
    personalGuarantee: true,
    approvalDifficulty: 'easy',
    bestFor: 'Simple no-fee travel rewards card',
    notes: null,
  },

  // ── US Bank ──────────────────────────────────────────────
  {
    issuerId: 'us_bank',
    name: 'US Bank Business Triple Cash Rewards',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 15,
    aprPostPromo: 19.24,
    creditLimitMin: 1000,
    creditLimitMax: 25000,
    creditLimitTypical: 8000,
    scoreMinimum: 660,
    revenueMinimum: 25000,
    businessAgeMinimum: 6,
    rewardsType: 'cash_back',
    rewardsRate: 3.0,
    rewardsDetails: '3% on gas, office supply, cell phone/internet/cable, restaurants; 1% all other',
    welcomeBonus: '$500 cash back after $4,500 spend in 150 days',
    welcomeBonusValue: 500,
    personalGuarantee: true,
    approvalDifficulty: 'moderate',
    bestFor: 'Long 0% intro APR with broad 3% categories',
    notes: '15-month 0% APR is tied for longest among no-annual-fee cards.',
  },

  // ── Wells Fargo ──────────────────────────────────────────
  {
    issuerId: 'wells_fargo',
    name: 'Wells Fargo Signify Business Cash Card',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 12,
    aprPostPromo: 18.24,
    creditLimitMin: 500,
    creditLimitMax: 25000,
    creditLimitTypical: 8000,
    scoreMinimum: 640,
    revenueMinimum: 25000,
    businessAgeMinimum: 3,
    rewardsType: 'cash_back',
    rewardsRate: 2.0,
    rewardsDetails: '2% cash back on qualifying purchases, 1% all other',
    welcomeBonus: '$500 cash back after $5,000 spend in 3 months',
    welcomeBonusValue: 500,
    personalGuarantee: true,
    approvalDifficulty: 'easy',
    bestFor: 'Easy approval with competitive cash back',
    notes: null,
  },

  // ── Additional Cards for Diversity ───────────────────────
  {
    issuerId: 'discover',
    name: 'Discover it Business Card',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 12,
    aprPostPromo: 17.24,
    creditLimitMin: 500,
    creditLimitMax: 20000,
    creditLimitTypical: 7000,
    scoreMinimum: 640,
    revenueMinimum: 20000,
    businessAgeMinimum: 3,
    rewardsType: 'cash_back',
    rewardsRate: 2.0,
    rewardsDetails: '2% gas & restaurants, 1% all other (doubled first year via Cashback Match)',
    welcomeBonus: 'Unlimited Cashback Match at end of first year',
    welcomeBonusValue: 0,
    personalGuarantee: true,
    approvalDifficulty: 'easy',
    bestFor: 'First-year doubled rewards and easy approval',
    notes: 'Cashback Match effectively doubles all rewards year 1.',
  },
  {
    issuerId: 'td_bank',
    name: 'TD Business Solutions Visa',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 12,
    aprPostPromo: 18.24,
    creditLimitMin: 500,
    creditLimitMax: 15000,
    creditLimitTypical: 5000,
    scoreMinimum: 620,
    revenueMinimum: 15000,
    businessAgeMinimum: 3,
    rewardsType: 'cash_back',
    rewardsRate: 2.0,
    rewardsDetails: '2% on all purchases (no cap)',
    welcomeBonus: '$200 cash back after $1,000 spend in 90 days',
    welcomeBonusValue: 200,
    personalGuarantee: true,
    approvalDifficulty: 'easy',
    bestFor: 'Low barrier to entry with solid flat-rate rewards',
    notes: 'One of the lowest minimum FICO requirements among business cards.',
  },
  {
    issuerId: 'pnc',
    name: 'PNC Cash Rewards Visa Business',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 9,
    aprPostPromo: 19.24,
    creditLimitMin: 500,
    creditLimitMax: 15000,
    creditLimitTypical: 5000,
    scoreMinimum: 630,
    revenueMinimum: 15000,
    businessAgeMinimum: 3,
    rewardsType: 'cash_back',
    rewardsRate: 4.0,
    rewardsDetails: '4% gas, 3% restaurants, 2% office supply & recurring, 1.5% all other',
    welcomeBonus: '$200 cash back after $3,000 spend in 3 months',
    welcomeBonusValue: 200,
    personalGuarantee: true,
    approvalDifficulty: 'easy',
    bestFor: 'Gas and restaurant spending on a no-fee card',
    notes: null,
  },

  // ── Credit Unions ───────────────────────────────────────────
  {
    issuerId: 'navy_federal',
    name: 'Navy Federal Business Visa',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: null,
    aprIntroMonths: null,
    aprPostPromo: 18.0,
    creditLimitMin: 500,
    creditLimitMax: 50000,
    creditLimitTypical: 15000,
    scoreMinimum: 650,
    revenueMinimum: 15000,
    businessAgeMinimum: 6,
    rewardsType: 'cash_back',
    rewardsRate: 1.5,
    rewardsDetails: '1.5% cash back on all purchases',
    welcomeBonus: null,
    welcomeBonusValue: null,
    personalGuarantee: true,
    approvalDifficulty: 'easy',
    bestFor: 'Military-affiliated businesses seeking no-fee rewards card',
    notes: 'Military/DoD affiliation required. APR range 11.15-18%. Generous CLI for members.',
  },
  {
    issuerId: 'alliant',
    name: 'Alliant Visa Business',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 12,
    aprPostPromo: 17.99,
    creditLimitMin: 500,
    creditLimitMax: 35000,
    creditLimitTypical: 12000,
    scoreMinimum: 680,
    revenueMinimum: 25000,
    businessAgeMinimum: 6,
    rewardsType: 'cash_back',
    rewardsRate: 2.5,
    rewardsDetails: '2.5% cash back on all purchases',
    welcomeBonus: null,
    welcomeBonusValue: null,
    personalGuarantee: true,
    approvalDifficulty: 'moderate',
    bestFor: 'High flat-rate cashback with 0% intro APR',
    notes: 'Open membership via $5 Foster Care to Success donation. APR range 13.99-17.99%.',
  },
  {
    issuerId: 'penfed',
    name: 'PenFed Platinum Business Rewards',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 15,
    aprPostPromo: 17.99,
    creditLimitMin: 500,
    creditLimitMax: 50000,
    creditLimitTypical: 15000,
    scoreMinimum: 670,
    revenueMinimum: 25000,
    businessAgeMinimum: 6,
    rewardsType: 'points',
    rewardsRate: 1.5,
    rewardsDetails: '1.5x points on all purchases',
    welcomeBonus: null,
    welcomeBonusValue: null,
    personalGuarantee: true,
    approvalDifficulty: 'moderate',
    bestFor: 'Long 0% intro period with points rewards',
    notes: 'Open membership via $5 National Military Family Association savings account. APR range 14.99-17.99%.',
  },
  {
    issuerId: 'becu',
    name: 'BECU Business Visa',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: null,
    aprIntroMonths: null,
    aprPostPromo: 15.24,
    creditLimitMin: 500,
    creditLimitMax: 25000,
    creditLimitTypical: 10000,
    scoreMinimum: 640,
    revenueMinimum: 15000,
    businessAgeMinimum: 6,
    rewardsType: 'cash_back',
    rewardsRate: 1.5,
    rewardsDetails: '1.5% cash back on all purchases',
    welcomeBonus: null,
    welcomeBonusValue: null,
    personalGuarantee: true,
    approvalDifficulty: 'easy',
    bestFor: 'Low APR no-fee business card for WA state businesses',
    notes: 'Washington state residency/employment required. APR range 12.24-15.24%.',
  },
  {
    issuerId: 'first_tech',
    name: 'First Tech FCU Business Rewards',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: 0,
    aprIntroMonths: 12,
    aprPostPromo: 18.0,
    creditLimitMin: 500,
    creditLimitMax: 40000,
    creditLimitTypical: 12000,
    scoreMinimum: 680,
    revenueMinimum: 25000,
    businessAgeMinimum: 6,
    rewardsType: 'points',
    rewardsRate: 2.0,
    rewardsDetails: '2x points on gas and grocery, 1x all other purchases',
    welcomeBonus: null,
    welcomeBonusValue: null,
    personalGuarantee: true,
    approvalDifficulty: 'moderate',
    bestFor: 'Bonus rewards on gas and grocery with 0% intro APR',
    notes: 'Membership via tech industry employer or Computer History Museum ($50). APR range 13.24-18%.',
  },
  {
    issuerId: 'lake_michigan_cu',
    name: 'Lake Michigan CU Business Visa',
    cardType: 'business_credit',
    annualFee: 0,
    annualFeeWaivedY1: false,
    aprIntro: null,
    aprIntroMonths: null,
    aprPostPromo: 15.99,
    creditLimitMin: 500,
    creditLimitMax: 25000,
    creditLimitTypical: 8000,
    scoreMinimum: 640,
    revenueMinimum: 15000,
    businessAgeMinimum: 6,
    rewardsType: null,
    rewardsRate: null,
    rewardsDetails: null,
    welcomeBonus: null,
    welcomeBonusValue: null,
    personalGuarantee: true,
    approvalDifficulty: 'easy',
    bestFor: 'Low-rate no-fee business card with easy membership',
    notes: 'Open membership via $5 ALS of Michigan donation. No rewards. APR range 10.99-15.99%.',
  },
];

async function seedCardProducts(): Promise<void> {
  console.log('Seeding card products...');

  for (const card of CARD_SEEDS) {
    await prisma.cardProduct.upsert({
      where: {
        id: `${card.issuerId}-${card.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '')}`,
      },
      update: {
        cardType: card.cardType,
        annualFee: dec(card.annualFee),
        annualFeeWaivedY1: card.annualFeeWaivedY1,
        aprIntro: card.aprIntro !== null ? dec(card.aprIntro) : null,
        aprIntroMonths: card.aprIntroMonths,
        aprPostPromo: card.aprPostPromo !== null ? dec(card.aprPostPromo) : null,
        creditLimitMin: card.creditLimitMin,
        creditLimitMax: card.creditLimitMax,
        creditLimitTypical: card.creditLimitTypical,
        scoreMinimum: card.scoreMinimum,
        revenueMinimum: dec(card.revenueMinimum),
        businessAgeMinimum: card.businessAgeMinimum,
        rewardsType: card.rewardsType,
        rewardsRate: card.rewardsRate !== null ? dec(card.rewardsRate) : null,
        rewardsDetails: card.rewardsDetails,
        welcomeBonus: card.welcomeBonus,
        welcomeBonusValue: card.welcomeBonusValue !== null ? dec(card.welcomeBonusValue) : null,
        personalGuarantee: card.personalGuarantee,
        approvalDifficulty: card.approvalDifficulty,
        bestFor: card.bestFor,
        isActive: true,
        notes: card.notes,
      },
      create: {
        id: `${card.issuerId}-${card.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '')}`,
        issuerId: card.issuerId,
        name: card.name,
        cardType: card.cardType,
        annualFee: dec(card.annualFee),
        annualFeeWaivedY1: card.annualFeeWaivedY1,
        aprIntro: card.aprIntro !== null ? dec(card.aprIntro) : null,
        aprIntroMonths: card.aprIntroMonths,
        aprPostPromo: card.aprPostPromo !== null ? dec(card.aprPostPromo) : null,
        creditLimitMin: card.creditLimitMin,
        creditLimitMax: card.creditLimitMax,
        creditLimitTypical: card.creditLimitTypical,
        scoreMinimum: card.scoreMinimum,
        revenueMinimum: dec(card.revenueMinimum),
        businessAgeMinimum: card.businessAgeMinimum,
        rewardsType: card.rewardsType,
        rewardsRate: card.rewardsRate !== null ? dec(card.rewardsRate) : null,
        rewardsDetails: card.rewardsDetails,
        welcomeBonus: card.welcomeBonus,
        welcomeBonusValue: card.welcomeBonusValue !== null ? dec(card.welcomeBonusValue) : null,
        personalGuarantee: card.personalGuarantee,
        approvalDifficulty: card.approvalDifficulty,
        bestFor: card.bestFor,
        isActive: true,
        notes: card.notes,
      },
    });
  }

  console.log(`  Seeded ${CARD_SEEDS.length} card products.`);
}

seedCardProducts()
  .then(() => {
    console.log('Card product seed complete.');
    return prisma.$disconnect();
  })
  .catch((err) => {
    console.error('Seed failed:', err);
    return prisma.$disconnect().then(() => process.exit(1));
  });

export { CARD_SEEDS, seedCardProducts };
