'use client';

// ============================================================
// GenerateDocumentModal — Reusable AI document generation modal
// Used across CapitalForge for all Claude-powered document gen.
// Flow: idle → generating → review/edit → save/copy/download
// ============================================================

import { useState } from 'react';
import { generateDocument, type GenerateDocumentParams, type GeneratedDocument } from '@/lib/claude-document-service';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  documentType: GenerateDocumentParams['type'];
  documentTitle: string;
  context: Record<string, unknown>;
  tone?: GenerateDocumentParams['tone'];
  length?: GenerateDocumentParams['length'];
  onSave?: (doc: GeneratedDocument) => void;
}

export function GenerateDocumentModal({
  isOpen, onClose, documentType, documentTitle,
  context, tone = 'professional', length = 'standard', onSave,
}: Props) {
  const [phase, setPhase] = useState<'idle' | 'generating' | 'review' | 'error'>('idle');
  const [doc, setDoc] = useState<GeneratedDocument | null>(null);
  const [editedContent, setEditedContent] = useState('');
  const [error, setError] = useState('');
  const [toast, setToast] = useState<string | null>(null);

  const showToast = (msg: string) => { setToast(msg); setTimeout(() => setToast(null), 3000); };

  const handleGenerate = async () => {
    setPhase('generating');
    setError('');
    try {
      const result = await generateDocument({ type: documentType, context, tone, length });
      setDoc(result);
      setEditedContent(result.content);
      setPhase('review');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Generation failed');
      setPhase('error');
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(editedContent);
    showToast('Copied to clipboard');
  };

  const handleDownload = () => {
    const blob = new Blob([editedContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = window.document.createElement('a');
    a.href = url;
    a.download = `${documentType}_${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    showToast('Downloaded');
  };

  const handleSave = () => {
    if (doc && onSave) {
      onSave({ ...doc, content: editedContent });
    }
    showToast('Saved to Document Vault');
    setTimeout(() => onClose(), 500);
  };

  const handleClose = () => {
    setPhase('idle');
    setDoc(null);
    setEditedContent('');
    setError('');
    onClose();
  };

  if (!isOpen) return null;

  return (
    <>
      {toast && (
        <div className="fixed top-6 right-6 z-[60] rounded-lg bg-emerald-600 px-4 py-3 text-sm font-medium text-white shadow-lg">
          {toast}
        </div>
      )}

      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60">
        <div className="bg-[#1a1f2e] border border-gray-700 rounded-xl w-full max-w-3xl max-h-[90vh] flex flex-col shadow-2xl">

          {/* Header */}
          <div className="flex items-center justify-between px-6 py-4 border-b border-gray-700">
            <div>
              <h2 className="text-white font-semibold text-lg">{documentTitle}</h2>
              <p className="text-gray-400 text-sm mt-0.5">Generated by Claude AI · CapitalForge</p>
            </div>
            <button onClick={handleClose} className="text-gray-400 hover:text-white text-xl leading-none p-1">×</button>
          </div>

          {/* Body */}
          <div className="flex-1 overflow-y-auto px-6 py-5">

            {phase === 'idle' && (
              <div className="text-center py-12">
                <div className="w-16 h-16 bg-[#D4A843]/10 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-3xl">✦</span>
                </div>
                <h3 className="text-white font-medium mb-2">Ready to generate</h3>
                <p className="text-gray-400 text-sm mb-6 max-w-md mx-auto">
                  Claude will draft this document using the client data on file.
                  You can review and edit before saving or sending.
                </p>
                <button
                  onClick={handleGenerate}
                  className="bg-[#D4A843] hover:bg-[#c49a38] text-black font-semibold px-8 py-3 rounded-lg transition-colors"
                >
                  Generate with Claude
                </button>
              </div>
            )}

            {phase === 'generating' && (
              <div className="text-center py-12">
                <div className="w-12 h-12 border-2 border-[#D4A843] border-t-transparent rounded-full animate-spin mx-auto mb-4" />
                <p className="text-white font-medium">Claude is drafting your document...</p>
                <p className="text-gray-400 text-sm mt-2">This usually takes 5–15 seconds</p>
              </div>
            )}

            {phase === 'review' && (
              <div>
                <div className="flex items-center justify-between mb-3">
                  <span className="text-green-400 text-sm font-medium">✓ Draft ready — review and edit below</span>
                  <span className="text-gray-500 text-xs">{editedContent.split(/\s+/).length} words</span>
                </div>
                <textarea
                  value={editedContent}
                  onChange={(e) => setEditedContent(e.target.value)}
                  className="w-full h-96 bg-[#0d1117] border border-gray-600 rounded-lg p-4 text-gray-200 text-sm font-mono leading-relaxed resize-none focus:outline-none focus:border-[#D4A843]"
                  spellCheck
                />
                <p className="text-gray-500 text-xs mt-2">
                  You can edit this draft. All edits are yours — Claude has provided a starting point.
                </p>
              </div>
            )}

            {phase === 'error' && (
              <div className="text-center py-12">
                <div className="w-12 h-12 bg-red-500/10 rounded-full flex items-center justify-center mx-auto mb-4">
                  <span className="text-red-400 text-xl">!</span>
                </div>
                <p className="text-red-400 font-medium mb-2">Generation failed</p>
                <p className="text-gray-400 text-sm mb-4">{error}</p>
                <button onClick={handleGenerate} className="text-[#D4A843] hover:underline text-sm">
                  Try again
                </button>
              </div>
            )}
          </div>

          {/* Footer */}
          {phase === 'review' && (
            <div className="flex items-center justify-between px-6 py-4 border-t border-gray-700">
              <div className="flex gap-2">
                <button onClick={handleGenerate} className="text-gray-400 hover:text-white text-sm border border-gray-600 px-3 py-1.5 rounded-lg transition-colors">
                  Regenerate
                </button>
                <button onClick={handleCopy} className="text-gray-400 hover:text-white text-sm border border-gray-600 px-3 py-1.5 rounded-lg transition-colors">
                  Copy
                </button>
                <button onClick={handleDownload} className="text-gray-400 hover:text-white text-sm border border-gray-600 px-3 py-1.5 rounded-lg transition-colors">
                  Download .txt
                </button>
              </div>
              <button
                onClick={handleSave}
                className="bg-[#D4A843] hover:bg-[#c49a38] text-black font-semibold px-6 py-2 rounded-lg transition-colors"
              >
                Save to Document Vault
              </button>
            </div>
          )}
        </div>
      </div>
    </>
  );
}
