// ============================================================
// CapitalForge — Tax Document & Reporting Generator
//
// Produces accountant-ready tax artifacts for a business's
// credit card stacking strategy:
//
//   • IRC §163(j) deductibility calculation report
//     — Pulls interest expense from CostCalculations
//     — Full computation via computeIRC163j()
//
//   • Year-end fee summary by card
//     — Annual fees, cash advance fees, program fees
//     — Aggregated from CardApplications + CostCalculations
//
//   • Accountant-ready export package (JSON + CSV)
//     — Single downloadable artifact for tax preparer
//
//   • Business-purpose documentation summary
//     — Substantiates deductions via SpendTransactions
//     — Maps merchant / MCC to business purpose narratives
//
// This is a financial modeling tool — not legal or tax advice.
// Always engage a qualified CPA or tax attorney.
// ============================================================

import { prisma } from '../config/database.js';
import logger from '../config/logger.js';
import {
  computeIRC163j,
  requiresIRC163jAlert,
} from './irc163j.js';
import type { IRC163jResult } from './irc163j.js';

// ── Types ─────────────────────────────────────────────────────────────────────

export interface IRC163jReportInput {
  businessId: string;
  tenantId: string;
  taxYear: number;
  adjustedTaxableIncome: number;
  businessInterestIncome: number;
  floorPlanFinancingInterest?: number;
  priorYearCarryforward?: number;
  averageAnnualGrossReceipts?: number;
  effectiveTaxRate?: number;
}

export interface CardFeeSummary {
  cardApplicationId: string;
  issuer: string;
  cardProduct: string;
  creditLimit: number | null;
  annualFee: number;
  cashAdvanceFee: number;
  introApr: number | null;
  regularApr: number | null;
  introAprExpiry: Date | null;
  totalFeesForYear: number;
}

export interface YearEndFeeSummary {
  businessId: string;
  taxYear: number;
  generatedAt: Date;
  cardSummaries: CardFeeSummary[];
  programFees: number;
  percentOfFundingFees: number;
  processorFees: number;
  totalAnnualFees: number;
  totalCashAdvanceFees: number;
  totalProgramFees: number;
  grandTotalCost: number;
  irc163jEstimate: {
    totalInterestExpense: number;
    deductibleInterest: number;
    disallowedAmount: number;
    limitationFlag: string;
  } | null;
}

export interface BusinessPurposeEntry {
  transactionId: string;
  transactionDate: Date;
  merchantName: string | null;
  mccCategory: string | null;
  amount: number;
  businessPurpose: string | null;
  isCashLike: boolean;
  flagged: boolean;
  substantiationNote: string;
}

export interface BusinessPurposeSummary {
  businessId: string;
  taxYear: number;
  generatedAt: Date;
  totalTransactions: number;
  totalAmount: number;
  documentedAmount: number;
  undocumentedAmount: number;
  cashLikeTransactionsCount: number;
  flaggedTransactionsCount: number;
  entries: BusinessPurposeEntry[];
  substantiationScore: number; // 0–100
  recommendations: string[];
}

export interface IRC163jReport {
  businessId: string;
  taxYear: number;
  generatedAt: Date;
  businessName: string;
  ein: string | null;
  entityType: string;
  computation: IRC163jResult;
  requiresAlert: boolean;
  interestExpenseComponents: {
    creditCardInterest: number;
    programFees: number;
    cashAdvanceFees: number;
    annualFees: number;
    processorFees: number;
    totalBusinessInterestExpense: number;
  };
  taxPlanningNotes: string[];
  disclaimer: string;
}

export interface TaxExportPackage {
  businessId: string;
  taxYear: number;
  exportedAt: Date;
  format: 'json' | 'csv';
  irc163jReport: IRC163jReport | null;
  yearEndFeeSummary: YearEndFeeSummary;
  businessPurposeSummary: BusinessPurposeSummary;
  metadata: {
    generatedBy: string;
    version: string;
    disclaimer: string;
  };
}

// ── Constants ─────────────────────────────────────────────────────────────────

const TAX_DISCLAIMER =
  'This document is generated by CapitalForge for informational purposes only. ' +
  'It does not constitute legal, tax, or financial advice. ' +
  'Consult a qualified CPA or tax attorney before filing.';

const SERVICE_VERSION = '1.0.0';

// ── Service Class ─────────────────────────────────────────────────────────────

export class TaxDocumentService {
  // ── IRC §163(j) Deductibility Report ────────────────────────────────────────

  async generateIRC163jReport(input: IRC163jReportInput): Promise<IRC163jReport> {
    const { businessId, tenantId, taxYear } = input;

    logger.info('Generating IRC §163(j) report', { businessId, tenantId, taxYear });

    // Fetch business metadata
    const business = await prisma.business.findFirst({
      where: { id: businessId, tenantId },
      select: {
        legalName: true,
        ein: true,
        entityType: true,
      },
    });

    if (!business) {
      throw new Error(`Business ${businessId} not found for tenant ${tenantId}.`);
    }

    // Fetch latest CostCalculation for interest expense components
    const costCalc = await prisma.costCalculation.findFirst({
      where: { businessId },
      orderBy: { createdAt: 'desc' },
    });

    // Derive interest expense from cost calculation fields
    const creditCardInterest = costCalc
      ? Number(costCalc.effectiveApr ?? 0) * Number(costCalc.totalCost) * 0.6 // estimated interest portion
      : 0;
    const programFees = costCalc ? Number(costCalc.programFees) : 0;
    const cashAdvanceFees = costCalc ? Number(costCalc.cashAdvanceFees) : 0;
    const annualFees = costCalc ? Number(costCalc.annualFees) : 0;
    const processorFees = costCalc ? Number(costCalc.processorFees) : 0;

    // Total business interest expense = interest charges + qualifying fees
    // Per §163(j), "business interest expense" includes amounts treated as
    // interest under Treas. Reg. §1.163(j)-1(b)(3).
    const totalBusinessInterestExpense =
      creditCardInterest + cashAdvanceFees + processorFees;

    // Run §163(j) computation
    const computation = computeIRC163j(
      {
        adjustedTaxableIncome: input.adjustedTaxableIncome,
        businessInterestExpense: totalBusinessInterestExpense,
        businessInterestIncome: input.businessInterestIncome,
        floorPlanFinancingInterest: input.floorPlanFinancingInterest ?? 0,
        priorYearCarryforward: input.priorYearCarryforward ?? 0,
        taxYear,
        averageAnnualGrossReceipts: input.averageAnnualGrossReceipts,
      },
      input.effectiveTaxRate ?? 0.21,
    );

    const requiresAlert = requiresIRC163jAlert(computation);

    // Build tax planning notes
    const taxPlanningNotes = buildTaxPlanningNotes(computation, taxYear);

    return {
      businessId,
      taxYear,
      generatedAt: new Date(),
      businessName: business.legalName,
      ein: business.ein,
      entityType: business.entityType,
      computation,
      requiresAlert,
      interestExpenseComponents: {
        creditCardInterest,
        programFees,
        cashAdvanceFees,
        annualFees,
        processorFees,
        totalBusinessInterestExpense,
      },
      taxPlanningNotes,
      disclaimer: TAX_DISCLAIMER,
    };
  }

  // ── Year-End Fee Summary ──────────────────────────────────────────────────────

  async generateYearEndFeeSummary(
    businessId: string,
    tenantId: string,
    taxYear: number,
  ): Promise<YearEndFeeSummary> {
    logger.info('Generating year-end fee summary', { businessId, tenantId, taxYear });

    // Verify business ownership
    const business = await prisma.business.findFirst({
      where: { id: businessId, tenantId },
      select: { id: true },
    });
    if (!business) {
      throw new Error(`Business ${businessId} not found for tenant ${tenantId}.`);
    }

    // Fetch approved/active card applications
    const applications = await prisma.cardApplication.findMany({
      where: {
        businessId,
        status: { in: ['approved', 'active', 'funded'] },
      },
      orderBy: { decidedAt: 'asc' },
    });

    // Fetch latest cost calculation for program/processor fees
    const costCalc = await prisma.costCalculation.findFirst({
      where: { businessId },
      orderBy: { createdAt: 'desc' },
    });

    // Build per-card summaries
    const cardSummaries: CardFeeSummary[] = applications.map((app) => {
      const annualFee = Number(app.annualFee ?? 0);
      const cashAdvanceFee = Number(app.cashAdvanceFee ?? 0);
      return {
        cardApplicationId: app.id,
        issuer: app.issuer,
        cardProduct: app.cardProduct,
        creditLimit: app.creditLimit ? Number(app.creditLimit) : null,
        annualFee,
        cashAdvanceFee,
        introApr: app.introApr ? Number(app.introApr) : null,
        regularApr: app.regularApr ? Number(app.regularApr) : null,
        introAprExpiry: app.introAprExpiry,
        totalFeesForYear: annualFee + cashAdvanceFee,
      };
    });

    const totalAnnualFees = cardSummaries.reduce((s, c) => s + c.annualFee, 0);
    const totalCashAdvanceFees = cardSummaries.reduce((s, c) => s + c.cashAdvanceFee, 0);
    const programFees = costCalc ? Number(costCalc.programFees) : 0;
    const percentOfFundingFees = costCalc ? Number(costCalc.percentOfFunding) : 0;
    const processorFees = costCalc ? Number(costCalc.processorFees) : 0;
    const totalProgramFees = programFees + percentOfFundingFees + processorFees;
    const grandTotalCost = costCalc ? Number(costCalc.totalCost) : 0;

    // Quick §163(j) estimate using cost calc data
    let irc163jEstimate: YearEndFeeSummary['irc163jEstimate'] = null;
    if (costCalc?.irc163jImpact !== null && costCalc?.irc163jImpact !== undefined) {
      const irc163jImpact = Number(costCalc.irc163jImpact);
      irc163jEstimate = {
        totalInterestExpense: totalCashAdvanceFees + (grandTotalCost * 0.6),
        deductibleInterest: irc163jImpact,
        disallowedAmount: Math.max(0, totalCashAdvanceFees - irc163jImpact),
        limitationFlag: irc163jImpact > 0 ? 'within_safe_zone' : 'no_limitation',
      };
    }

    return {
      businessId,
      taxYear,
      generatedAt: new Date(),
      cardSummaries,
      programFees,
      percentOfFundingFees,
      processorFees,
      totalAnnualFees,
      totalCashAdvanceFees,
      totalProgramFees,
      grandTotalCost,
      irc163jEstimate,
    };
  }

  // ── Business-Purpose Documentation Summary ───────────────────────────────────

  async generateBusinessPurposeSummary(
    businessId: string,
    tenantId: string,
    taxYear: number,
  ): Promise<BusinessPurposeSummary> {
    logger.info('Generating business purpose summary', { businessId, tenantId, taxYear });

    const yearStart = new Date(taxYear, 0, 1);
    const yearEnd = new Date(taxYear + 1, 0, 1);

    const transactions = await prisma.spendTransaction.findMany({
      where: {
        businessId,
        tenantId,
        transactionDate: { gte: yearStart, lt: yearEnd },
      },
      orderBy: { transactionDate: 'asc' },
    });

    let totalAmount = 0;
    let documentedAmount = 0;
    let undocumentedAmount = 0;
    let cashLikeCount = 0;
    let flaggedCount = 0;

    const entries: BusinessPurposeEntry[] = transactions.map((tx) => {
      const amount = Number(tx.amount);
      totalAmount += amount;
      const hasDoc = Boolean(tx.businessPurpose && tx.businessPurpose.trim().length > 0);
      if (hasDoc) documentedAmount += amount; else undocumentedAmount += amount;
      if (tx.isCashLike) cashLikeCount++;
      if (tx.flagged) flaggedCount++;

      return {
        transactionId: tx.id,
        transactionDate: tx.transactionDate,
        merchantName: tx.merchantName,
        mccCategory: tx.mccCategory,
        amount,
        businessPurpose: tx.businessPurpose,
        isCashLike: tx.isCashLike,
        flagged: tx.flagged,
        substantiationNote: buildSubstantiationNote(tx),
      };
    });

    const substantiationScore = computeSubstantiationScore(
      transactions.length,
      documentedAmount,
      totalAmount,
      cashLikeCount,
      flaggedCount,
    );

    const recommendations = buildSubstantiationRecommendations(
      substantiationScore,
      cashLikeCount,
      flaggedCount,
      undocumentedAmount,
    );

    return {
      businessId,
      taxYear,
      generatedAt: new Date(),
      totalTransactions: transactions.length,
      totalAmount,
      documentedAmount,
      undocumentedAmount,
      cashLikeTransactionsCount: cashLikeCount,
      flaggedTransactionsCount: flaggedCount,
      entries,
      substantiationScore,
      recommendations,
    };
  }

  // ── Accountant Export Package ─────────────────────────────────────────────────

  async generateExportPackage(
    businessId: string,
    tenantId: string,
    taxYear: number,
    irc163jInput?: Omit<IRC163jReportInput, 'businessId' | 'tenantId' | 'taxYear'>,
  ): Promise<TaxExportPackage> {
    logger.info('Generating tax export package', { businessId, tenantId, taxYear });

    // Fetch all components in parallel
    const [yearEndFeeSummary, businessPurposeSummary] = await Promise.all([
      this.generateYearEndFeeSummary(businessId, tenantId, taxYear),
      this.generateBusinessPurposeSummary(businessId, tenantId, taxYear),
    ]);

    // 163j report is optional — requires ATI input
    let irc163jReport: IRC163jReport | null = null;
    if (irc163jInput) {
      irc163jReport = await this.generateIRC163jReport({
        ...irc163jInput,
        businessId,
        tenantId,
        taxYear,
      });
    }

    return {
      businessId,
      taxYear,
      exportedAt: new Date(),
      format: 'json',
      irc163jReport,
      yearEndFeeSummary,
      businessPurposeSummary,
      metadata: {
        generatedBy: 'CapitalForge Tax Document Generator',
        version: SERVICE_VERSION,
        disclaimer: TAX_DISCLAIMER,
      },
    };
  }

  // ── CSV Serializer ────────────────────────────────────────────────────────────

  serializeToCSV(pkg: TaxExportPackage): string {
    const lines: string[] = [];

    // Header block
    lines.push('CapitalForge Tax Export Package');
    lines.push(`Business ID,${pkg.businessId}`);
    lines.push(`Tax Year,${pkg.taxYear}`);
    lines.push(`Exported At,${pkg.exportedAt.toISOString()}`);
    lines.push(`Disclaimer,${pkg.metadata.disclaimer}`);
    lines.push('');

    // Year-end fee summary
    lines.push('=== YEAR-END FEE SUMMARY ===');
    lines.push('Issuer,Card Product,Credit Limit,Annual Fee,Cash Advance Fee,Total Fees');
    for (const card of pkg.yearEndFeeSummary.cardSummaries) {
      lines.push(
        [
          csvEscape(card.issuer),
          csvEscape(card.cardProduct),
          card.creditLimit ?? '',
          card.annualFee,
          card.cashAdvanceFee,
          card.totalFeesForYear,
        ].join(','),
      );
    }
    lines.push('');
    lines.push(`Total Annual Fees,${pkg.yearEndFeeSummary.totalAnnualFees}`);
    lines.push(`Total Cash Advance Fees,${pkg.yearEndFeeSummary.totalCashAdvanceFees}`);
    lines.push(`Total Program Fees,${pkg.yearEndFeeSummary.totalProgramFees}`);
    lines.push(`Grand Total Cost,${pkg.yearEndFeeSummary.grandTotalCost}`);
    lines.push('');

    // Business purpose summary
    lines.push('=== BUSINESS PURPOSE DOCUMENTATION ===');
    lines.push(
      'Transaction ID,Date,Merchant,MCC Category,Amount,Business Purpose,Cash-Like,Flagged,Note',
    );
    for (const entry of pkg.businessPurposeSummary.entries) {
      lines.push(
        [
          entry.transactionId,
          entry.transactionDate.toISOString().split('T')[0],
          csvEscape(entry.merchantName ?? ''),
          csvEscape(entry.mccCategory ?? ''),
          entry.amount,
          csvEscape(entry.businessPurpose ?? ''),
          entry.isCashLike ? 'YES' : 'NO',
          entry.flagged ? 'YES' : 'NO',
          csvEscape(entry.substantiationNote),
        ].join(','),
      );
    }
    lines.push('');
    lines.push(`Substantiation Score,${pkg.businessPurposeSummary.substantiationScore}/100`);
    lines.push('');

    // 163j report block
    if (pkg.irc163jReport) {
      const r = pkg.irc163jReport;
      lines.push('=== IRC §163(j) DEDUCTIBILITY REPORT ===');
      lines.push(`Business Name,${csvEscape(r.businessName)}`);
      lines.push(`EIN,${r.ein ?? 'N/A'}`);
      lines.push(`Entity Type,${r.entityType}`);
      lines.push(`ATI Definition,${r.computation.atiDefinition}`);
      lines.push(`Is Exempt,${r.computation.isExempt}`);
      lines.push(`ATI Limit (30% of ATI),${r.computation.atiLimit}`);
      lines.push(`Deductibility Limit,${r.computation.deductibilityLimit}`);
      lines.push(`Total Interest Subject to Limit,${r.computation.totalInterestSubjectToLimit}`);
      lines.push(`Deductible Interest,${r.computation.deductibleInterest}`);
      lines.push(`Disallowed Amount,${r.computation.disallowedAmount}`);
      lines.push(`Updated Carryforward,${r.computation.updatedCarryforward}`);
      lines.push(`Limitation Flag,${r.computation.limitationFlag}`);
      lines.push(`Projected Tax Impact,${r.computation.projectedTaxImpactOfDisallowance}`);
      lines.push(`Narrative,${csvEscape(r.computation.narrative)}`);
    }

    return lines.join('\n');
  }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

type SpendTx = {
  merchantName: string | null;
  mccCategory: string | null;
  businessPurpose: string | null;
  isCashLike: boolean;
  flagged: boolean;
  flagReason: string | null;
};

function buildSubstantiationNote(tx: SpendTx): string {
  if (tx.flagged && tx.flagReason) {
    return `FLAGGED: ${tx.flagReason}`;
  }
  if (tx.isCashLike) {
    return 'Cash-like transaction — requires enhanced substantiation per §162.';
  }
  if (!tx.businessPurpose) {
    return 'No business purpose documented. Add before tax filing.';
  }
  return `Documented: ${tx.businessPurpose}`;
}

function computeSubstantiationScore(
  total: number,
  documentedAmount: number,
  totalAmount: number,
  cashLikeCount: number,
  flaggedCount: number,
): number {
  if (total === 0) return 100;
  let score = totalAmount > 0 ? (documentedAmount / totalAmount) * 100 : 100;
  score -= cashLikeCount * 2;
  score -= flaggedCount * 5;
  return Math.round(Math.max(0, Math.min(100, score)));
}

function buildSubstantiationRecommendations(
  score: number,
  cashLikeCount: number,
  flaggedCount: number,
  undocumentedAmount: number,
): string[] {
  const recs: string[] = [];
  if (undocumentedAmount > 0) {
    recs.push(
      `Document the business purpose for $${undocumentedAmount.toLocaleString()} in undocumented transactions.`,
    );
  }
  if (cashLikeCount > 0) {
    recs.push(
      `${cashLikeCount} cash-like transaction(s) require enhanced documentation — ` +
        'retain receipts and written business purpose statements.',
    );
  }
  if (flaggedCount > 0) {
    recs.push(
      `${flaggedCount} flagged transaction(s) should be reviewed by your tax advisor ` +
        'before including in deductions.',
    );
  }
  if (score < 70) {
    recs.push(
      'Substantiation score is below 70. Consider implementing a real-time expense ' +
        'documentation workflow to strengthen audit defense.',
    );
  }
  if (recs.length === 0) {
    recs.push('Business purpose documentation is strong. No immediate action required.');
  }
  return recs;
}

function buildTaxPlanningNotes(result: IRC163jResult, taxYear: number): string[] {
  const notes: string[] = [];

  if (result.isExempt) {
    notes.push(
      'Business qualifies for the §163(j) small-business exemption — no limitation applies.',
    );
    return notes;
  }

  notes.push(`ATI definition for ${taxYear}: ${result.atiDefinition}`);

  if (result.disallowedAmount > 0) {
    notes.push(
      `$${result.disallowedAmount.toLocaleString()} of interest is disallowed and carries forward indefinitely. ` +
        'This amount will reduce next year\'s deductible interest.',
    );
  }

  if (result.limitationFlag === 'approaching_limit') {
    notes.push(
      'Interest expense is approaching the §163(j) cap. Consider paying down balances before year-end, ' +
        'timing large cash advances into the next tax year, or evaluating the RPTOB election if eligible.',
    );
  }

  if (result.projectedTaxImpactOfDisallowance > 0) {
    notes.push(
      `Estimated tax cost of disallowance: $${result.projectedTaxImpactOfDisallowance.toLocaleString()} ` +
        '(assumes 21% federal rate). Actual impact depends on effective blended rate.',
    );
  }

  if (taxYear >= 2022) {
    notes.push(
      'Post-2022: Depreciation and amortization are NOT added back to ATI when computing ' +
        'the 30% cap. This reduces the deductible limit versus pre-2022 rules.',
    );
  }

  return notes;
}

function csvEscape(value: string): string {
  if (value.includes(',') || value.includes('"') || value.includes('\n')) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

// ── Singleton export ──────────────────────────────────────────────────────────

export const taxDocumentService = new TaxDocumentService();
